### PR TITLE
Add Bluebox-ng install script for Kali 2 GNU/Linux

### PR DESCRIPTION
**Pull request by aancw**
This script updated for Kali 2 GNU/Linux reference to this issue https://github.com/jesusprubio/bluebox-ng/issues/57. Already tested in Kali 2 GNU/Linux with bluebox-ng source code from https://github.com/jesusprubio/bluebox-ng

### CODE REVIEW

**Comment by jesusprubio** [comment]
Cool! Thanks!!! :)

**Comment by jesusprubio** [comment]
Ey dude, could you please also to remove the old one and update the link into README? :)

But wait, I'm giving you permissions in the repo, this way you can avoid the PRs. Welcome!! BTW, I've sent you an invitation to a Slack group in which we're speaking about the whole thing. Channel #bluebox-ng. See you there!

**Comment by aancw** [comment]
I'm use kali2.sh instead of kali.sh because i don't tested in old Kali GNU/Linux. But, if you are want to target Kali 2 GNU/Linux then i will update.

Thanks for inviting me to your project and Slack group.

**Comment by jesusprubio** [comment]
Yes, IMHO we can drop it, it's time to update. If we both agree of course. :)

**Pull request merged**
